function P_event = event_probability(p)

P_event = p.tau_r*p.p0_r + (1-p.tau_r)*p.p1_r + ...
          p.tau_w*p.p0_w + (1-p.tau_w)*p.p1_w + ...
          p.tau_v*p.p0_v + (1-p.tau_v)*p.p1_v + ...
          p.tau_m*p.p0_m + (1-p.tau_m)*p.p1_m;

end
